"""Primitives shared by every ValKit module: canonical serialisation, hashing,
time and identifier generation.

Everything that ends up in an audit trail, a hash chain or a generated
document is serialised through :func:`canonical_json` so that the same logical
record always produces the same bytes, and therefore the same SHA-256. Byte
stability is what makes the evidence chain verifiable years later on a
different machine.
"""

from __future__ import annotations

import base64
import dataclasses
import datetime as _dt
import enum
import hashlib
import json
import os
import re
import uuid
from typing import Any, Callable, Iterable, Mapping

__all__ = [
    "Clock",
    "SystemClock",
    "FrozenClock",
    "canonical_json",
    "sha256_bytes",
    "sha256_text",
    "sha256_file",
    "sha256_obj",
    "utc_now",
    "parse_utc",
    "format_utc",
    "new_id",
    "slugify",
    "to_jsonable",
    "deep_get",
    "redact",
]


# --------------------------------------------------------------------------
# Time
# --------------------------------------------------------------------------


class Clock:
    """Source of UTC timestamps.

    Injected rather than called directly so that every artefact ValKit
    produces can be regenerated byte-for-byte in a test.
    """

    def now(self) -> _dt.datetime:  # pragma: no cover - interface
        raise NotImplementedError

    def now_iso(self) -> str:
        return format_utc(self.now())


class SystemClock(Clock):
    """Wall-clock UTC."""

    def now(self) -> _dt.datetime:
        return _dt.datetime.now(_dt.timezone.utc)


class FrozenClock(Clock):
    """Deterministic clock for tests and reproducible regeneration.

    Each call advances by ``step`` seconds so that ordered events keep a
    strictly increasing timestamp without becoming non-deterministic.
    """

    def __init__(self, start: str | _dt.datetime = "2026-01-01T00:00:00Z", step: float = 1.0):
        self._t = parse_utc(start) if isinstance(start, str) else start.astimezone(_dt.timezone.utc)
        self._step = step

    def now(self) -> _dt.datetime:
        current = self._t
        self._t = self._t + _dt.timedelta(seconds=self._step)
        return current


def utc_now() -> _dt.datetime:
    return _dt.datetime.now(_dt.timezone.utc)


def format_utc(value: _dt.datetime) -> str:
    """Render a datetime as a Zulu ISO-8601 string with second precision.

    21 CFR 11.50(a)(2) requires the signed record to show the date and time of
    signing; ValKit always records and displays UTC so that an inspector never
    has to reason about the signer's local offset.
    """
    if value.tzinfo is None:
        value = value.replace(tzinfo=_dt.timezone.utc)
    value = value.astimezone(_dt.timezone.utc).replace(microsecond=0)
    return value.strftime("%Y-%m-%dT%H:%M:%SZ")


def parse_utc(value: str) -> _dt.datetime:
    """Parse an ISO-8601 timestamp, accepting a trailing ``Z``."""
    text = value.strip()
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    parsed = _dt.datetime.fromisoformat(text)
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=_dt.timezone.utc)
    return parsed.astimezone(_dt.timezone.utc)


# --------------------------------------------------------------------------
# Serialisation
# --------------------------------------------------------------------------


def to_jsonable(value: Any) -> Any:
    """Convert dataclasses, enums, datetimes, sets and bytes into JSON types."""
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, enum.Enum):
        return to_jsonable(value.value)
    if isinstance(value, _dt.datetime):
        return format_utc(value)
    if isinstance(value, _dt.date):
        return value.isoformat()
    if isinstance(value, bytes):
        return base64.b64encode(value).decode("ascii")
    if dataclasses.is_dataclass(value) and not isinstance(value, type):
        out: dict[str, Any] = {}
        for field in dataclasses.fields(value):
            if field.metadata.get("exclude"):
                continue
            out[field.name] = to_jsonable(getattr(value, field.name))
        return out
    if isinstance(value, Mapping):
        return {str(k): to_jsonable(v) for k, v in value.items()}
    if isinstance(value, (set, frozenset)):
        return sorted(to_jsonable(v) for v in value)
    if isinstance(value, Iterable):
        return [to_jsonable(v) for v in value]
    if hasattr(value, "to_dict"):
        return to_jsonable(value.to_dict())
    return str(value)


def canonical_json(value: Any) -> str:
    """Serialise to the canonical form used for every hash in ValKit.

    Keys sorted, no insignificant whitespace, UTF-8 preserved. Two records
    that are logically equal hash identically regardless of how they were
    constructed.
    """
    return json.dumps(
        to_jsonable(value),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    )


# --------------------------------------------------------------------------
# Hashing
# --------------------------------------------------------------------------


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_text(text: str) -> str:
    return sha256_bytes(text.encode("utf-8"))


def sha256_obj(value: Any) -> str:
    """SHA-256 of the canonical JSON form of ``value``."""
    return sha256_text(canonical_json(value))


def sha256_file(path: str | os.PathLike[str], chunk_size: int = 1 << 20) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


# --------------------------------------------------------------------------
# Identifiers
# --------------------------------------------------------------------------

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(text: str, max_length: int = 64) -> str:
    slug = _SLUG_RE.sub("-", text.strip().lower()).strip("-")
    return slug[:max_length] or "item"


def new_id(prefix: str, entropy: Callable[[], str] | None = None) -> str:
    """Generate a prefixed identifier.

    ``entropy`` is injectable so a deterministic sequence can be supplied in
    tests; the default is a UUID4 suffix.
    """
    suffix = entropy() if entropy is not None else uuid.uuid4().hex[:12]
    return f"{prefix}-{suffix}"


# --------------------------------------------------------------------------
# Misc helpers
# --------------------------------------------------------------------------


def deep_get(mapping: Mapping[str, Any], path: str, default: Any = None) -> Any:
    """Look up ``a.b.c`` in nested mappings, returning ``default`` if absent."""
    current: Any = mapping
    for part in path.split("."):
        if not isinstance(current, Mapping) or part not in current:
            return default
        current = current[part]
    return current


_SECRET_KEYS = {"password", "secret", "token", "api_key", "apikey", "credential", "otp"}


def redact(value: Any) -> Any:
    """Recursively replace secret-looking values before they reach a log.

    The audit trail is a permanent record. Anything that looks like the second
    component of an electronic signature must never enter it.
    """
    if isinstance(value, Mapping):
        return {
            k: ("***REDACTED***" if str(k).lower() in _SECRET_KEYS else redact(v))
            for k, v in value.items()
        }
    if isinstance(value, (list, tuple)):
        return [redact(v) for v in value]
    return value
